version: "3.9"
services:
    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    # laravel:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile  # Reference your Dockerfile here
    #     ports:
    #         - 8000:80  # Adjust the port as needed
    #     depends_on:
    #         - mysql
    #     volumes:
    #         - .:/var/www/html
